alias f='find . -name'
alias cd..='cd ..'
alias control='sudo unity-control-center && fg'
alias diff='colordiff'
alias off='sudo shutdown -h now'
alias res='sudo shutdown -r now'
alias size='sudo du -h --max-depth=1'
