alias f='find . -name'
alias cd..='cd ..'
alias control='sudo unity-control-center && fg'
alias diff='colordiff'
alias size='sudo du -h --max-depth=1'
alias esi-sdk_release='cat /data/esi/etc/esi-sdk_release'
alias esi-sdk_content='cat /data/esi/scripts/esi-sdk_content'
