alias f='find . -name'
alias cd..='cd ..'
alias control='sudo gnome-control-center && fg'
alias diff='colordiff'
alias size='sudo du -h --max-depth=1'
alias g='grep -rn --exclude=tags --exclude=output.map'
alias gi='grep -rni --exclude=tags --exclude=output.map'
alias tags='/usr/bin/ctags-universal -R'
