#!/bin/bash

abort()
{
	echo -e "\nFailed to install some packages\n" 
}

trap 'abort' 0
set -e
   
sudo apt update
sudo apt -y upgrade
sudo apt -y autoremove
sudo apt -y install ssh meld ubuntu-restricted-extras gedit-plugins gitk minicom wget unzip zip \
	colordiff vim openssh-server \
	gparted cmake flex curl konsole

# Boost libray
#sudo apt -y install libboost-all-dev

# Packages for Yocto host development
#sudo apt -y install autotools-dev universal-ctags libssl-dev subversion ccache libtool build-essential libicu-dev \
#sudo apt -y install gawk diffstat texinfo g++-multilib gcc-multilib bison chrpath socat xterm \
#cpio libsdl1.2-dev libelf-dev

# Packages for uboot development
#sudo apt -y install u-boot-tools lzop gnupg module-init-tools openconnect device-tree-compiler \
#icu-devtools expect

# install android tools
#sudo apt -y install android-tools-adb android-tools-fastboot

# install ebook converter
#sudo apt -y install calibre

#insatll video player and codecs
sudo apt -y install libvulkan1 mesa-vulkan-drivers vulkan-tools mpv

echo -e "\nInstallation finished\n"

trap : 0
