#!/bin/bash

abort()
{
	echo -e "\nFailed to install some packages\n" 
}

trap 'abort' 0
set -e
   
sudo apt update
sudo apt -y upgrade
sudo apt -y autoremove
sudo apt -y install ssh meld ubuntu-restricted-extras gedit-plugins minicom wget unzip zip \
	colordiff vim openssh-server gparted cmake flex curl konsole

# Boost libray
#sudo apt -y install libboost-all-dev

# Packages for Yocto host development
#sudo apt -y install autotools-dev universal-ctags libssl-dev subversion ccache libtool build-essential libicu-dev \
#sudo apt -y install gawk diffstat texinfo g++-multilib gcc-multilib bison chrpath socat xterm \
#cpio libsdl1.2-dev libelf-dev

# Packages for ESP32 development
sudo apt -y install git flex bison gperf python3-pip python3-venv ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

# install android tools
#sudo apt -y install android-tools-adb android-tools-fastboot

# install ebook converter
#sudo apt -y install calibre

#insatll video player and codecs
sudo apt -y install mpv libvulkan1 mesa-vulkan-drivers vulkan-tools 

echo -e "\nInstallation finished\n"

trap : 0
