#!/bin/bash

dir=$PWD

gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'

sudo apt install fonts-powerline

#list of files to make symlink to them:
files=".bash_aliases .gitconfig .vimrc .vim"

for file in $files; do
	echo "Creating symlink to $file in user's home directory"
	ln -fs $dir/$file ~/$file 2>/dev/null
done

#installing vundle package manager for vim
if [ ! -d "$dir/.vim/bundle/vundle" ]; then
	echo "Installing vundle for vim"
	git clone https://github.com/gmarik/vundle.git .vim/bundle/vundle 1>/dev/null
fi

echo "Creating symlink to diff-so-fancy in /usr/local/bin directory"
sudo ln -fs $dir/diff-so-fancy /usr/local/bin/diff-so-fancy 2>/dev/null

if ! grep -Fq "bash-functions" ~/.bashrc; then
	echo "" >> ~/.bashrc
	echo "if [ -f ~/dotconfigs/bash-functions ]; then" >> ~/.bashrc
	echo "  . ~/dotconfigs/bash-functions" >> ~/.bashrc
	echo "fi" >> ~/.bashrc
	# Adding dirtrim by the way
	echo "" >> ~/.bashrc
	echo "PROMPT_DIRTRIM=2" >> ~/.bashrc
fi


echo -e "\nIn vim enter the command: :PluginInstall"
echo -e "Finished\n"
